pipeline {
  agent any

  tools{
     maven 'Maven 3.6.2'
  }

  stages{
      stage("build){
          steps{
              echo 'step 1 Build'
	      dir('worker')	
		sh 'mvn compile'
          }
      }
      stage(test){
          steps{
              echo 'step 2 test'
	      dir('worker')
	      	sh 'mvn clean test'
          }
      }
      stage(package){
          steps{
              echo 'step 3'
	      dir('worker')
	      	sh 'mvn package -DskipTests'
          }
      }
  }

  post{
    always{
        echo 'Building multi branch pipeline.'
    }
  }
}
